module.exports = {
  projects: [
    '<rootDir>/apps/clinic',
    '<rootDir>/libs/web/patient',
    '<rootDir>/libs/common/core',
    '<rootDir>/libs/web/ui/form',
    '<rootDir>/libs/web/ui/grid',
    '<rootDir>/libs/web/ui/dataview',
    '<rootDir>/libs/common/core/json-schema',
    '<rootDir>/libs/commonui/core/core',
    '<rootDir>/libs/commonui/core',
    '<rootDir>/libs/commonui/core/testing',
    '<rootDir>/libs/commonui/core/json-schema',
    '<rootDir>/libs/commonui/core/select',
    '<rootDir>/libs/common/ui/form/core',
    '<rootDir>/libs/web/ui/material',
    '<rootDir>/libs/web/form/material',
    '<rootDir>/libs/web/ui/form/material',
    '<rootDir>/libs/web/ui/form/sync',
    '<rootDir>/libs/common/lookup',
    '<rootDir>/libs/web/ui/grid/grid',
    '<rootDir>/apps/ems',
    '<rootDir>/libs/web/ui/drawer',
  ],
};
